title: Sizhe Wang
logo: "/images/Sizhe Wang Photo.jpg?raw=true" 
description: > # welcome to check my Resume, LinkedIn, GitHub content!

  <a href="https://www.linkedin.com/in/sizhe-wang-509a5a242//">LinkedIn</a> 
  <br>
  <a href="pdf/Sizhe Wang.pdf"btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/sizhewanglehigh/">GitHub</a>  
  <br>

  
theme: jekyll-theme-minimal
