title: Sizhe Wang # your name (or website title) here
logo: "/images/deb85b36138469ef689ed65860789c5.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/sizhe-wang-509a5a242//">LinkedIn</a> 
  <br>
  <a href="pdf/Sizhe Wang Resume.pdf"btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/sizhewanglehigh/">GitHub</a>  
  <br>

  
theme: jekyll-theme-minimal
